### PR TITLE
allow client to override processResponse or processRecords

### PR DESCRIPTION
**Pull request by szinck**
processResponse - allows access to aws kinesis response
processRecords - allows access to just records for a simpler client interface

### CODE REVIEW

**Comment by evansolomon** [comment]
Sorry it's taken me so long to look at this. It came right as I was traveling a bunch.

Just wanted to say thanks for putting the PR together and let you know I'll get to it this weekend.

**Comment by evansolomon** [comment]
Obviously didn't get to this over the weekend as planned. Sorry!

Just for clarity, here are the things I'm wondering about

1. I think `ConsumerExtension#processResponse` should be optional so that just defining `processRecords` is still a valid extension.
2. I don't think `ProcessRecordsCallback` is the right type for the callback in `processResponse` (as it will be getting a whole response, not just records).

**Comment by szinck** [comment]
#1 - I made that optional
#2 - I'm not sure what the right type of callback would be.  With the current callback you can pass it true if  you want it to do checkpointing.  My original thought was just to preserve the same capability - whether it's processRecord or processResponse, just pass true to the callback if you want it to checkpoint.  Does this sound ok or what do you think should happen here?

**Comment by evansolomon** [comment]
Yea you're right about everything. Sloppy reading on my part.

**Comment by evansolomon** [comment]
Published on npm as version 0.3.0.

Thanks for the PR!

**Comment by szinck** [comment]
Awesome, Thank you!

**Pull request merged**
